apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-qt5a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-qt5a
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-qt5a
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-qt5a
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-qt5a
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tbrt-tenant/rhtap-demo-app/hacbs-test-project-qt5a@sha256:a6c48971348cdc67edf06503fbc7a9336284c1b361a4e598deb9622c87589c3e
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
